# Generated by Django 3.2.4 on 2021-06-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Deparment',
            new_name='Department',
        ),
    ]
